# 01. Exploratory Data Analysis (EDA)

**Team Role**: Member 1

### Purpose:
This notebook is dedicated to exploratory data analysis of the challenge datasets across the provided sources once the official files are available. It will inspect data distributions, missingness, schema characteristics, entity overlap, and attribute consistency without modifying raw challenge files.

In [4]:
import pandas as pd

In [5]:
TRAIN_PATH =  r"C:\Users\HP\Desktop\Niharika\6ab10eb3b23ba_student_resource\student_resource\dataset\train"

In [6]:
train_s1 = pd.read_csv(
    f"{TRAIN_PATH}/train_source1.tsv",
    sep="\t",
    nrows=1000
)

In [7]:
train_s2 = pd.read_csv(
    f"{TRAIN_PATH}/train_source2.tsv",
    sep="\t",
    nrows=1000
)

train_s3 = pd.read_csv(
    f"{TRAIN_PATH}/train_source3.tsv",
    sep="\t",
    nrows=1000
)

ground_truth = pd.read_csv(
    f"{TRAIN_PATH}/train_ground_truth.tsv",
    sep="\t",
    nrows=1000
)

In [10]:
train_s1.shape

(1000, 4)

In [11]:
train_s1.columns

Index(['entity_id', 'business_name', 'business_address', 'country'], dtype='str')

In [12]:
print("SOURCE 1")
print(train_s1.columns.tolist())

print("\nSOURCE 2")
print(train_s2.columns.tolist())

print("\nSOURCE 3")
print(train_s3.columns.tolist())

print("\nGROUND TRUTH")
print(ground_truth.columns.tolist())

SOURCE 1
['entity_id', 'business_name', 'business_address', 'country']

SOURCE 2
['entity_id', 'business_name', 'business_address', 'country']

SOURCE 3
['entity_id', 'business_name', 'business_address', 'country']

GROUND TRUTH
['source1_entity_id', 'matched_entity_ids']

In [13]:
print("===== SOURCE 1 =====")
display(train_s1.head(10))

print("===== SOURCE 2 =====")
display(train_s2.head(10))

print("===== SOURCE 3 =====")
display(train_s3.head(10))

print("===== GROUND TRUTH =====")
display(ground_truth.head(10))

===== SOURCE 1 =====

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India
5,S1-851869949,Custom Wealth Services LLC,"OH, Columbus, 5559 Orville Avenue",US
6,S1-785847572,Consulting Nyasa Nursing Private Limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",India
7,S1-27541239,Nexus Anchor Rain,"1111 Church Street, Unit 2007, Nashville, TN",US
8,S1-629417405,Moore Bitwise Inc,"337 Oakland Avenue, Michigan City, IN",US
9,S1-22305073,Dermatology Green Medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",US

===== SOURCE 2 =====

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US
5,S2-138046867,Lee and Lawson,"1702 Pine Avenue, CITY OF MENOMONIE, WI",US
6,S2-584977605,SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...,"H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab",India
7,S2-277444929,Shree Infracon Private Ltd,"63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKH...",India
8,S2-721031885,Chavira Platinum Chimera LLC,"282 SAXONY DRIVE, FTT MITCHELL, KY",US
9,S2-508602797,FOUNDATION EXCEL AGENCY PRIVATE LIMITED,"HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, M...",India

===== SOURCE 3 =====

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India
5,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US
6,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US
7,S3-249416830,Ectolumdrex dba X+ Madison Inc,"S03575 Cty Tk M, Town Of Buffalo, WI",US
8,S3-107644605,Animal Hanisch Hospirlg,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri",US
9,S3-160217003,Gomez Optimal,"343 Hempstead 161, Hope, Arkansas",US

===== GROUND TRUTH =====

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [14]:
print("SOURCE 1")
train_s1.info()

print("\nSOURCE 2")
train_s2.info()

print("\nSOURCE 3")
train_s3.info()

print("\nGROUND TRUTH")
ground_truth.info()

SOURCE 1
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   entity_id         1000 non-null   str
 1   business_name     1000 non-null   str
 2   business_address  1000 non-null   str
 3   country           1000 non-null   str
dtypes: str(4)
memory usage: 121.0 KB

SOURCE 2
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   entity_id         1000 non-null   str
 1   business_name     1000 non-null   str
 2   business_address  965 non-null    str
 3   country           1000 non-null   str
dtypes: str(4)
memory usage: 122.6 KB

SOURCE 3
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   entity_id         1000 non-null   str
 1   business_name     1000 non-null   str
 2   business_address  963 non-null    str
 3   country           1000 non-null   str
dtypes: str(4)
memory usage: 120.5 KB

GROUND TRUTH
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   source1_entity_id   1000 non-null   str
 1   matched_entity_ids  953 non-null    str
dtypes: str(2)
memory usage: 69.8 KB

In [15]:
print("===== MISSING VALUES =====")

print("\nSOURCE 1")
print(train_s1.isnull().sum())

print("\nSOURCE 2")
print(train_s2.isnull().sum())

print("\nSOURCE 3")
print(train_s3.isnull().sum())

print("\nGROUND TRUTH")
print(ground_truth.isnull().sum())

===== MISSING VALUES =====

SOURCE 1
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

SOURCE 2
entity_id            0
business_name        0
business_address    35
country              0
dtype: int64

SOURCE 3
entity_id            0
business_name        0
business_address    37
country              0
dtype: int64

GROUND TRUTH
source1_entity_id      0
matched_entity_ids    47
dtype: int64

In [17]:
print("===== DUPLICATE ENTITY IDs =====")

print("Source 1:", train_s1["entity_id"].duplicated().sum())
print("Source 2:", train_s2["entity_id"].duplicated().sum())
print("Source 3:", train_s3["entity_id"].duplicated().sum())

===== DUPLICATE ENTITY IDs =====
Source 1: 0
Source 2: 0
Source 3: 0

In [18]:
print("===== SOURCE 1 COUNTRIES =====")
print(train_s1["country"].value_counts(dropna=False).head(20))

print("\n===== SOURCE 2 COUNTRIES =====")
print(train_s2["country"].value_counts(dropna=False).head(20))

print("\n===== SOURCE 3 COUNTRIES =====")
print(train_s3["country"].value_counts(dropna=False).head(20))

===== SOURCE 1 COUNTRIES =====
country
US       595
India    405
Name: count, dtype: int64

===== SOURCE 2 COUNTRIES =====
country
US       604
India    396
Name: count, dtype: int64

===== SOURCE 3 COUNTRIES =====
country
US       593
India    407
Name: count, dtype: int64

In [19]:
print("===== SOURCE 1 BUSINESS NAMES =====")
display(train_s1[["entity_id", "business_name"]].sample(20, random_state=42))

print("===== SOURCE 2 BUSINESS NAMES =====")
display(train_s2[["entity_id", "business_name"]].sample(20, random_state=42))

print("===== SOURCE 3 BUSINESS NAMES =====")
display(train_s3[["entity_id", "business_name"]].sample(20, random_state=42))

===== SOURCE 1 BUSINESS NAMES =====

        entity_id                            business_name
521  S1-695737678               Paschal and Liu Associates
737  S1-470699785                    Krystyna's Energy Inc
740  S1-842881175                        Mandie Cannon, DO
660  S1-359497386                            Shakti Global
411  S1-483140947      Highland Continental Photonics Inc.
678  S1-829163315                     Silver Barbershop PC
626  S1-609323033                             Batts Global
513  S1-713966229  Red Vision Construction Private Limited
859  S1-568217118                         Simms Osisko Inc
136  S1-613598143                         Clair Sprott Inc
811  S1-193918319                         Keiser Abrdn LLC
76   S1-630223771                    All International LLP
636  S1-589521969                      Ranice Haw Star Mfa
973   S1-25587016                Beacon Highland Solar LLC
938  S1-256480068          Kshatriya (India) Logistics LLP
899  S1-122618676                       Rodgers Westin Inc
280  S1-989439466                   Value Digital Concepts
883  S1-367965660                 Poole, Goe and Voss, LLC
761  S1-623350674                 K 7 Classic Painting LLC
319  S1-225119054    Complete Certified Pharmaceutical LLC

===== SOURCE 2 BUSINESS NAMES =====

        entity_id                                     business_name
521  S2-274109622                   Shree Trust Industries Services
737  S2-192696208                                    NIRVNA ART LTD
740   S2-17298657                     Laxmi  Foundation (ID: 10654)
660  S2-330756776                Shri Satyaraj Media Limited Center
411  S2-661443009  Rebekah Phillbisbs Supreme Choice Group Partners
678  S2-273475397                              प्राइम भारत सर्विसेज
626  S2-231688856                              Tech Trading Private
513  S2-799199580                           Gaynor Walton, DMD Inc.
859   S2-23854429                              Classic &-Associates
136  S2-102286733                      Digital Foundation (Limited)
811  S2-381127815               CORP IRONWORKERS UNION LOCAL NO 854
76   S2-571714424                               lochravengolden.com
636  S2-764329448               Brush, Jillene, M.D. Northside Corp
973  S2-592650888                         Nice Laxmi Public Limited
938  S2-812894315             BANGALORE NORMH FARMS PRIVATE LIMITED
899  S2-994612767                   ROXIE'S PINNACLE CREAM SERVICES
280  S2-716687956                Pediatric Dental Group Inc. Center
883  S2-549354680             Balakrishnan Adancnd Australia (P.C.)
761  S2-575536430                Orr Interfaith Ministries Services
319  S2-937703023            Symphony  Distributors Private Limited

===== SOURCE 3 BUSINESS NAMES =====

        entity_id                             business_name
521  S3-904865577         Shri Srm Software Ventures [Pvt.]
737  S3-441640276                   Housing Fellowship Corp
740  S3-405814914                               biex l.l.c.
660  S3-304954093                Vision Better Cénter Group
411  S3-201614402                Ramirez Vanguard Ralty Inc
678  S3-435438494                               Alagu Sángh
626  S3-812130826                    *** researchnexola.com
513  S3-898759711                Co Commission on Education
859  S3-502330452          -- Sputnik Engineers Private Ltd
136  S3-791460119                Rapid Select Solutions Inc
811  S3-558115814                    Timber Fhaabcsogy Inc.
76   S3-891585470                      Leahy Silver  Acp LP
636  S3-584580805                  Wilson and Yátes Plus LP
973  S3-803176614                 Jain Ventures Private Ltd
938  S3-950043411              Long Traders Exports Limited
899  S3-844266618             Anthony, Pope-&-Parker Spring
280  S3-444600693  M/s shiny medical centre private limited
883  S3-639651774                                 Gfalva Co
761  S3-521283666                        Gsb Advisors (Pvt)
319  S3-722381828       United United Partners Northside PC

In [20]:
print("===== SOURCE 1 ADDRESSES =====")
display(train_s1[["entity_id", "business_address"]].sample(20, random_state=42))

print("===== SOURCE 2 ADDRESSES =====")
display(train_s2[["entity_id", "business_address"]].sample(20, random_state=42))

print("===== SOURCE 3 ADDRESSES =====")
display(train_s3[["entity_id", "business_address"]].sample(20, random_state=42))

===== SOURCE 1 ADDRESSES =====

        entity_id                                   business_address
521  S1-695737678                 Albemarle, 1006 Charlotte Road, NC
737  S1-470699785  NY, Unit Apartment 206, 183 Main Street, Fredonia
740  S1-842881175               3315 Nelson Road, Town Of Algoma, WI
660  S1-359497386  2-40-314/C Ambedkar Nagar, Balamrai, Gymkhana,...
411  S1-483140947                1023 Gravel Lick Road, Sand Gap, KY
678  S1-829163315         230 Chapman Drive Extension, Asheville, NC
626  S1-609323033                      362 Ocean Parkway, Berlin, MD
513  S1-713966229  Plot No E 3/4 Floor- 1A Purnendu Nagar Po Anis...
859  S1-568217118               3113 Springdale Avenue, Glenview, IL
136  S1-613598143                      430 Lewis Avenue, Lombard, IL
811  S1-193918319                   15013 93rd Street, Vancouver, WA
76   S1-630223771  Office 105, Flr-1, Sujata Chambers, Abhaychand...
636  S1-589521969           TN, 200 Stewarts Chapel Road, Flintville
973   S1-25587016          69 Brayton Avenue, Unit 3, Fall River, MA
938  S1-256480068  H.No.24 A T Umbarni, Village Tal Kalyan Dist, ...
899  S1-122618676                   936 Emmer Street, Rolesville, NC
280  S1-989439466                    20464 Cooks Drive, Marshall, IL
883  S1-367965660                        195 Myers Drive, Gurley, AL
761  S1-623350674             3615 Jefferson Street, Kansas City, MO
319  S1-225119054        193 Maple Avenue, White Sulphur Springs, WV

===== SOURCE 2 ADDRESSES =====

        entity_id                                   business_address
521  S2-274109622  38 RAMACHACHANDRAROAD RS PURAM, COIMBATORE, Ta...
737  S2-192696208  117, GROUND FLOOR, HABIBULAH ROAD, OPP TO IFF,...
740   S2-17298657  PLOT NO. 16A. , SUBHASH NAGR NEAR HEERADAS BUS...
660  S2-330756776                                                NaN
411  S2-661443009                318 CEDAR ST, NORTH LITTLE ROCK, AR
678  S2-273475397  GREATER BOMBAY, EKTA MEDOWS, BLDG NO.1, KHATAU...
626  S2-231688856  F-0244 & 245, SECOND FLOOR, NEW RAJINDER NAGAR...
513  S2-799199580                      45 CRESTVIEW RD, COLUMBUS, OH
859   S2-23854429  Karnataka, #30, 1ST FLOOR, NANDI SUNSHINE, 4TH...
136  S2-102286733  HN #242 E-20, SHOP NO.24/85, 11 NO. STPO, ARER...
811  S2-381127815                   #196 ATKINSON RD, WALNUT DCP, IL
76   S2-571714424                 15-A TREEWAY COURT, LOCH RAVEN, MD
636  S2-764329448                 0016497 MARVINDALE ST, MINERVA, OH
973  S2-592650888  AL-129, 12TH MAIN ROAD, 2ND STREET SHANTHI COL...
938  S2-812894315  NO.4C-701, 4TH CROSS ROAD, 1ST BLOCK, HRBR LAY...
899  S2-994612767                      WV, PRINCETON, 7120 PISGAH RD
280  S2-716687956                  3327 BEDFORD LANE, MONTGOMERY, AL
883  S2-549354680                  MCKINLEY STREET, NULL, LORAIN, OH
761  S2-575536430                                MN, ORR, ECHO TRAIL
319  S2-937703023            H NO 1179, PANCHAKULA, HARYANA, हरियाणा

===== SOURCE 3 ADDRESSES =====

        entity_id                                   business_address
521  S3-904865577  Lotus Land Mark;66, Mutyalampadu Vja, Vijayawa...
737  S3-441640276    7152 Fuller Station Road, Schenectady, New York
740  S3-405814914                                                NaN
660  S3-304954093        469 Sweet Bay Ln, LAKE Havasu CIYT, Arizona
411  S3-201614402                       1 3rd St, Fosston, Minnesota
678  S3-435438494  Arun Academy Building, Jaipur, P.no. 6, Opp. J...
626  S3-812130826           9334 Ravenridge Rd, Parkvville, Maryland
513  S3-898759711    1180 Hlckory Flat Rd, Buckhannon, West Virginia
859  S3-502330452                                 G/3, Shahibaug, GJ
136  S3-791460119  W229s4474 Milky Way Road, Village Of Waukesha,...
811  S3-558115814                1925 Hllly Ave, Ontario, California
76   S3-891585470                   104 Tesoro Way, Del Valle, Texas
636  S3-584580805               Jack Rabbit Dr, Fort Mohave, Arizona
973  S3-803176614  Delhi, DL, New Delhi, A-195/1, Sf, Raju Park, ...
938  S3-950043411  Shop No. 51, Model Town B, Near Khandelwal Mis...
899  S3-844266618      16922 17th Avenue Court, Spanaway, Washington
280  S3-444600693             6C Short Street, Calcutta, WB, Kolkata
883  S3-639651774     2335 Haversham Close, Virginia Beach, Virginia
761  S3-521283666  H.no 41 Mumbai Samachar Margbharat Floorings, ...
319  S3-722381828         11615 19th Ave, Spokane Valley, Washington

In [21]:
display(ground_truth.head(20))

   source1_entity_id                                 matched_entity_ids
0          S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1        S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2       S1-343815751             S2-790675320,S2-479876582,S3-878454467
3       S1-656753428              S2-153058913,S2-24659151,S3-679606215
4       S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5        S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6       S1-318373630                          S2-660036492,S3-804600254
7        S1-86989137                          S3-274817120,S3-312496301
8        S1-29845983                          S2-648035184,S3-588502663
9       S1-789009573              S2-383871912,S3-74481402,S3-576451439
10      S1-730934468                          S2-356983532,S3-352439310
11        S1-7293388  S2-7028416,S2-442723188,S2-157073701,S3-523120965
12      S1-546142636  S2-487600131,S2-582477216,S2-392804085,S3-2000...
13      S1-274126313  S2-736616474,S2-680265918,S2-51486805,S3-92563...
14      S1-145361722              S2-120366543,S2-939389287,S3-96572514
15      S1-503957000  S2-994658326,S2-235117490,S2-353308450,S2-1732...
16      S1-692000596                          S2-580419223,S3-164220452
17      S1-561341312                          S2-483615364,S3-619529814
18      S1-777597828                          S2-836452886,S3-413669121
19      S1-282467635                          S2-938895481,S3-138350041

In [22]:
print("Number of ground-truth rows:", len(ground_truth))
print("Unique Source 1 IDs:", ground_truth["source1_entity_id"].nunique())

Number of ground-truth rows: 1000
Unique Source 1 IDs: 1000

In [23]:
print(
    ground_truth["source1_entity_id"].duplicated().sum()
)

0

In [24]:
for name, df in {
    "Source 1": train_s1,
    "Source 2": train_s2,
    "Source 3": train_s3,
    "Ground Truth": ground_truth
}.items():

    print(f"\n===== {name} =====")
    print((df.isnull().mean() * 100).round(2))

===== Source 1 =====
entity_id           0.0
business_name       0.0
business_address    0.0
country             0.0
dtype: float64

===== Source 2 =====
entity_id           0.0
business_name       0.0
business_address    3.5
country             0.0
dtype: float64

===== Source 3 =====
entity_id           0.0
business_name       0.0
business_address    3.7
country             0.0
dtype: float64

===== Ground Truth =====
source1_entity_id     0.0
matched_entity_ids    4.7
dtype: float64

In [25]:
for name, df in {
    "Source 1": train_s1,
    "Source 2": train_s2,
    "Source 3": train_s3
}.items():

    print(f"\n===== {name} =====")

    for col in ["business_name", "business_address", "country"]:
        empty_count = (
            df[col]
            .fillna("")
            .astype(str)
            .str.strip()
            .eq("")
            .sum()
        )

        print(f"{col}: {empty_count} empty values")

===== Source 1 =====
business_name: 0 empty values
business_address: 0 empty values
country: 0 empty values

===== Source 2 =====
business_name: 0 empty values
business_address: 35 empty values
country: 0 empty values

===== Source 3 =====
business_name: 0 empty values
business_address: 37 empty values
country: 0 empty values

In [26]:
for name, df in {
    "Source 1": train_s1,
    "Source 2": train_s2,
    "Source 3": train_s3
}.items():

    duplicate_ids = df["entity_id"].duplicated().sum()

    print(f"{name}: {duplicate_ids} duplicate entity IDs")

Source 1: 0 duplicate entity IDs
Source 2: 0 duplicate entity IDs
Source 3: 0 duplicate entity IDs

In [27]:
sample_gt = train_s1[["entity_id"]].merge(
    ground_truth,
    left_on="entity_id",
    right_on="source1_entity_id",
    how="left"
)

display(sample_gt.head(20))

       entity_id source1_entity_id matched_entity_ids
0   S1-925783039               NaN                NaN
1   S1-773889195               NaN                NaN
2   S1-377745466               NaN                NaN
3   S1-133037285               NaN                NaN
4   S1-755362802               NaN                NaN
5   S1-851869949               NaN                NaN
6   S1-785847572               NaN                NaN
7    S1-27541239               NaN                NaN
8   S1-629417405               NaN                NaN
9    S1-22305073               NaN                NaN
10  S1-504790211               NaN                NaN
11  S1-564729135               NaN                NaN
12  S1-236312382               NaN                NaN
13  S1-865131206               NaN                NaN
14  S1-626914593               NaN                NaN
15  S1-765734254               NaN                NaN
16   S1-82053739               NaN                NaN
17  S1-309349399               NaN                NaN
18  S1-221443075               NaN                NaN
19  S1-341506266               NaN                NaN

In [28]:
def count_matches(value):
    if pd.isna(value) or str(value).strip() == "":
        return 0

    return len(
        [x for x in str(value).split(",") if x.strip()]
    )

sample_gt["match_count"] = sample_gt["matched_entity_ids"].apply(count_matches)

display(
    sample_gt[["source1_entity_id", "matched_entity_ids", "match_count"]].head(20)
)

   source1_entity_id matched_entity_ids  match_count
0                NaN                NaN            0
1                NaN                NaN            0
2                NaN                NaN            0
3                NaN                NaN            0
4                NaN                NaN            0
5                NaN                NaN            0
6                NaN                NaN            0
7                NaN                NaN            0
8                NaN                NaN            0
9                NaN                NaN            0
10               NaN                NaN            0
11               NaN                NaN            0
12               NaN                NaN            0
13               NaN                NaN            0
14               NaN                NaN            0
15               NaN                NaN            0
16               NaN                NaN            0
17               NaN                NaN            0
18               NaN                NaN            0
19               NaN                NaN            0

In [29]:
def match_sources(value):
    if pd.isna(value) or str(value).strip() == "":
        return "none"

    ids = [x.strip() for x in str(value).split(",") if x.strip()]

    has_s2 = any(x.startswith("S2-") for x in ids)
    has_s3 = any(x.startswith("S3-") for x in ids)

    if has_s2 and has_s3:
        return "S2+S3"
    elif has_s2:
        return "S2"
    elif has_s3:
        return "S3"
    else:
        return "other"

sample_gt["match_source_type"] = sample_gt["matched_entity_ids"].apply(match_sources)

print(sample_gt["match_source_type"].value_counts())

match_source_type
none    1000
Name: count, dtype: int64

In [30]:
for name, df in {
    "Source 1": train_s1,
    "Source 2": train_s2,
    "Source 3": train_s3
}.items():

    name_lengths = df["business_name"].fillna("").astype(str).str.len()

    print(f"\n===== {name} business_name length =====")
    print(name_lengths.describe())

===== Source 1 business_name length =====
count    1000.000000
mean       23.877000
std         7.988723
min         6.000000
25%        18.000000
50%        23.000000
75%        30.000000
max        61.000000
Name: business_name, dtype: float64

===== Source 2 business_name length =====
count    1000.000000
mean       25.487000
std         9.003827
min         2.000000
25%        19.000000
50%        25.000000
75%        31.000000
max        72.000000
Name: business_name, dtype: float64

===== Source 3 business_name length =====
count    1000.000000
mean       25.134000
std         9.390752
min         2.000000
25%        18.000000
50%        25.000000
75%        32.000000
max        62.000000
Name: business_name, dtype: float64

In [31]:
for name, df in {
    "Source 1": train_s1,
    "Source 2": train_s2,
    "Source 3": train_s3
}.items():

    address_lengths = df["business_address"].fillna("").astype(str).str.len()

    print(f"\n===== {name} business_address length =====")
    print(address_lengths.describe())

===== Source 1 business_address length =====
count    1000.000000
mean       52.745000
std        25.893985
min        17.000000
25%        33.000000
50%        41.000000
75%        71.250000
max       168.000000
Name: business_address, dtype: float64

===== Source 2 business_address length =====
count    1000.000000
mean       46.004000
std        24.340675
min         0.000000
25%        30.000000
50%        37.000000
75%        61.000000
max       134.000000
Name: business_address, dtype: float64

===== Source 3 business_address length =====
count    1000.00000
mean       46.23200
std        21.72985
min         0.00000
25%        34.00000
50%        41.00000
75%        55.00000
max       157.00000
Name: business_address, dtype: float64