# 02. Data Preprocessing & Normalization

**Team Role**: Member 1

### Purpose:
This notebook focuses on developing, validating, and testing text and address normalization routines (such as case standardization, punctuation cleaning, business suffix handling, and address tokenization) to support candidate generation and feature extraction.

In [1]:
import pandas as pd
import re
import unicodedata

In [2]:
TRAIN_PATH = r"C:\Users\HP\Desktop\Niharika\6ab10eb3b23ba_student_resource\student_resource\dataset\train"

In [3]:
train_s1 = pd.read_csv(
    f"{TRAIN_PATH}/train_source1.tsv",
    sep="\t",
    nrows=1000
)

train_s2 = pd.read_csv(
    f"{TRAIN_PATH}/train_source2.tsv",
    sep="\t",
    nrows=1000
)

train_s3 = pd.read_csv(
    f"{TRAIN_PATH}/train_source3.tsv",
    sep="\t",
    nrows=1000
)

In [4]:
def normalize_text(value):
    """
    Basic Unicode-safe text normalization.

    Steps:
    1. Handle missing values
    2. Unicode normalization
    3. Case normalization
    4. Replace punctuation/symbols with spaces
    5. Collapse repeated whitespace
    """
    if pd.isna(value):
        return ""

    text = str(value)

    # Normalize Unicode representation
    text = unicodedata.normalize("NFKC", text)

    # Case-insensitive normalization while preserving Unicode
    text = text.casefold()

    # Replace punctuation/symbols with spaces.
    # \w preserves Unicode word characters.
    text = re.sub(r"[^\w\s]", " ", text, flags=re.UNICODE)

    # Collapse repeated whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [5]:
test_values = [
    "ABC Pvt. Ltd.",
    "ABC   PHARMACY",
    "A.B.C Pharmacy",
    "Shivshakti Vidyalaya",
    "International South Consultants Private Ltd",
    None
]

for value in test_values:
    print(f"{value!r}  ->  {normalize_text(value)!r}")

'ABC Pvt. Ltd.'  ->  'abc pvt ltd'
'ABC   PHARMACY'  ->  'abc pharmacy'
'A.B.C Pharmacy'  ->  'a b c pharmacy'
'Shivshakti Vidyalaya'  ->  'shivshakti vidyalaya'
'International South Consultants Private Ltd'  ->  'international south consultants private ltd'
None  ->  ''

In [6]:
test_values = [
    "ABC Pvt. Ltd.",
    "ABC   PHARMACY",
    "A.B.C Pharmacy",
    "Shivshakti Vidyalaya",
    "International South Consultants Private Ltd",
    None
]

for value in test_values:
    print(f"{value!r}  ->  {normalize_text(value)!r}")

'ABC Pvt. Ltd.'  ->  'abc pvt ltd'
'ABC   PHARMACY'  ->  'abc pharmacy'
'A.B.C Pharmacy'  ->  'a b c pharmacy'
'Shivshakti Vidyalaya'  ->  'shivshakti vidyalaya'
'International South Consultants Private Ltd'  ->  'international south consultants private ltd'
None  ->  ''

In [9]:
def normalize_name(value):
    """
    Normalize business names.
    """
    return normalize_text(value)


def normalize_address(value):
    """
    Normalize business addresses.
    """
    return normalize_text(value)


def normalize_country(value):
    """
    Normalize country values.
    """
    if pd.isna(value):
        return ""

    text = unicodedata.normalize("NFKC", str(value))
    text = text.casefold()
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [7]:
s1_clean = train_s1.copy()
s2_clean = train_s2.copy()
s3_clean = train_s3.copy()

In [10]:
for df in [s1_clean, s2_clean, s3_clean]:
    df["business_name_clean"] = df["business_name"].apply(normalize_name)
    df["business_address_clean"] = df["business_address"].apply(normalize_address)
    df["country_clean"] = df["country"].apply(normalize_country)

In [11]:
display(
    s1_clean[
        [
            "business_name",
            "business_name_clean",
            "business_address",
            "business_address_clean",
            "country",
            "country_clean"
        ]
    ].head(20)
)

,business_name,business_name_clean,business_address,business_address_clean,country,country_clean
0,Orelee's Barbershop,orelee s barbershop,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,US,us
1,Prime Money,prime money,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,US,us
2,B+ Retail Inc,b retail inc,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,US,us
3,Christ Chapel,christ chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,US,us
4,Prabhav Business Center,prabhav business center,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,India,india
5,Custom Wealth Services LLC,custom wealth services llc,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,US,us
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,India,india
7,Nexus Anchor Rain,nexus anchor rain,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,US,us
8,Moore Bitwise Inc,moore bitwise inc,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,US,us
9,Dermatology Green Medicine,dermatology green medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,US,us
10,Crystal Lending PC,crystal lending pc,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut,US,us
11,Dream Construction Limited,dream construction limited,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",h no 16 11 23 37 a 2nd floor flat no 207 sagar...,India,india
12,"Kelly Advisory, Inc",kelly advisory inc,"301 1st Street, Chokio, MN",301 1st street chokio mn,US,us
13,Helios,helios,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport ct,US,us
14,Unified Choice Dynamix,unified choice dynamix,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",unit building 3030 md 2701 eastern boulevard m...,US,us
15,Health Fellowship Partners,health fellowship partners,"601 Oleander Circle, Virginia Beach City, VA",601 oleander circle virginia beach city va,US,us
16,Smart Healthcare Private Limited,smart healthcare private limited,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...,India,india
17,Callicoat & Dailey Inc,callicoat dailey inc,"Charlotte, NC, 833 Reliance Street",charlotte nc 833 reliance street,US,us
18,Iris Advisors,iris advisors,House No-777 Raghubir Bhawanmadan Pur Khadar S...,house no 777 raghubir bhawanmadan pur khadar s...,India,india
19,Secunderabad Park Private Limited,secunderabad park private limited,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",secunderabad hyderabad plot no 53 flat no 402 ...,India,india

In [12]:
display(
    s1_clean[
        [
            "entity_id",
            "business_name",
            "business_name_clean",
            "business_address",
            "business_address_clean",
            "country",
            "country_clean"
        ]
    ].head(20)
)

,entity_id,business_name,business_name_clean,business_address,business_address_clean,country,country_clean
0,S1-925783039,Orelee's Barbershop,orelee s barbershop,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,US,us
1,S1-773889195,Prime Money,prime money,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,US,us
2,S1-377745466,B+ Retail Inc,b retail inc,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,US,us
3,S1-133037285,Christ Chapel,christ chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,US,us
4,S1-755362802,Prabhav Business Center,prabhav business center,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,India,india
5,S1-851869949,Custom Wealth Services LLC,custom wealth services llc,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,US,us
6,S1-785847572,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,India,india
7,S1-27541239,Nexus Anchor Rain,nexus anchor rain,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,US,us
8,S1-629417405,Moore Bitwise Inc,moore bitwise inc,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,US,us
9,S1-22305073,Dermatology Green Medicine,dermatology green medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,US,us
10,S1-504790211,Crystal Lending PC,crystal lending pc,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut,US,us
11,S1-564729135,Dream Construction Limited,dream construction limited,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",h no 16 11 23 37 a 2nd floor flat no 207 sagar...,India,india
12,S1-236312382,"Kelly Advisory, Inc",kelly advisory inc,"301 1st Street, Chokio, MN",301 1st street chokio mn,US,us
13,S1-865131206,Helios,helios,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport ct,US,us
14,S1-626914593,Unified Choice Dynamix,unified choice dynamix,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",unit building 3030 md 2701 eastern boulevard m...,US,us
15,S1-765734254,Health Fellowship Partners,health fellowship partners,"601 Oleander Circle, Virginia Beach City, VA",601 oleander circle virginia beach city va,US,us
16,S1-82053739,Smart Healthcare Private Limited,smart healthcare private limited,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...,India,india
17,S1-309349399,Callicoat & Dailey Inc,callicoat dailey inc,"Charlotte, NC, 833 Reliance Street",charlotte nc 833 reliance street,US,us
18,S1-221443075,Iris Advisors,iris advisors,House No-777 Raghubir Bhawanmadan Pur Khadar S...,house no 777 raghubir bhawanmadan pur khadar s...,India,india
19,S1-341506266,Secunderabad Park Private Limited,secunderabad park private limited,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",secunderabad hyderabad plot no 53 flat no 402 ...,India,india

In [14]:
print("Original S1 columns:")
print(train_s1.columns.tolist())

print("\nCleaned S1 columns:")
print(s1_clean.columns.tolist())

Original S1 columns:
['entity_id', 'business_name', 'business_address', 'country']

Cleaned S1 columns:
['entity_id', 'business_name', 'business_address', 'country', 'business_name_clean', 'business_address_clean', 'country_clean']

In [15]:
for name, df in {
    "Source 1": s1_clean,
    "Source 2": s2_clean,
    "Source 3": s3_clean
}.items():

    print(f"\n===== {name} =====")
    print("Empty names:",
          (df["business_name_clean"] == "").sum())
    print("Empty addresses:",
          (df["business_address_clean"] == "").sum())
    print("Empty countries:",
          (df["country_clean"] == "").sum())

===== Source 1 =====
Empty names: 0
Empty addresses: 0
Empty countries: 0

===== Source 2 =====
Empty names: 0
Empty addresses: 35
Empty countries: 0

===== Source 3 =====
Empty names: 0
Empty addresses: 37
Empty countries: 0

In [16]:
display(
    s2_clean[
        ["business_name", "business_name_clean"]
    ].head(10)
)

,business_name,business_name_clean
0,राम मार्केटिंग प्राइवेट लिमिटेड,र म म र क ट ग प र इव ट ल म ट ड
1,-- Holloway Peak Inc Seafood,holloway peak inc seafood
2,आदित्य प्रॉपर्टीज एलएलपी,आद त य प र पर ट ज एलएलप
3,Summit Inc,summit inc
4,Delta Tetlecommunication Inc,delta tetlecommunication inc
5,Lee and Lawson,lee and lawson
6,SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...,shivshakti vidyalaya vidyalaya overseas corpor...
7,Shree Infracon Private Ltd,shree infracon private ltd
8,Chavira Platinum Chimera LLC,chavira platinum chimera llc
9,FOUNDATION EXCEL AGENCY PRIVATE LIMITED,foundation excel agency private limited

In [22]:
from pathlib import Path
import sys

SRC_PATH = (
    Path.cwd()
    / ".."
    / "code"
    / "business_entity_resolution"
    / "src"
)

sys.path.append(str(SRC_PATH.resolve()))

from preprocessing import (
    normalize_text,
    normalize_name,
    normalize_address,
    normalize_country
)

ImportError: cannot import name 'normalize_name' from 'preprocessing' (C:\Users\HP\Desktop\ml\code\business_entity_resolution\src\preprocessing.py)